---
title: "DataCleaning"
author: "Owen Salciccioli, Kristin Prunty, Rachel Holman"
date: "10/5/2022"
output: html_document
---
## This RMD has all the data cleaning for our project

### Load in Libraries
```{r}
library(tidyverse)
library(caret)
library(randomForest)
library(lubridate)
library(ggthemes)
```

### Read in Data
```{r}
source('DataCleaning.R')
```

## Code to create retention variables - DO NOT RUN, just pull dataset from GIT
```{r}
DonorHistory_Annual <- DonorHistory_Clean %>%
  filter(Credit.Amount < 10000)

a <- Sys.time()
findYears <- function(e) {
  entityYears <- DonorHistory_Annual %>%
    filter(Entity.ID == e) %>%
    select(Fiscal.Year) %>%
    arrange(Fiscal.Year)
  entityYearsVector = as.vector(entityYears[,1])
  entityYearsVector
}

RetainedByYear <- function() {
  uniqueEntity <- unique(DonorHistory_Annual$Entity.ID)
  fulldata <- data.frame('Entity.ID'=character(), 'Year'= integer(),
                         'OneYearRetention'= logical(), 'ThreeYearRetention'= logical(), 'FiveYearRetention'= logical())
  r = 1
  for (e in uniqueEntity) {
    entityYearsVector <- unique(findYears(e))
    for (i in 1:length(entityYearsVector)) {
      if (i == 1) {
        OneYear = F
        ThreeYear = F
        FiveYear = F
      }
      else if(entityYearsVector[i] - entityYearsVector[i-1] == 1) {
        OneYear = T
        ThreeYear = T
        FiveYear = T
      }
      else if (entityYearsVector[i] - entityYearsVector[i-1] <= 3) {
        ThreeYear = T
        FiveYear = T
        OneYear = F
      }
      else if (entityYearsVector[i] - entityYearsVector[i-1] <= 5) {
        FiveYear = T
        ThreeYear = F
        OneYear = F
      }
      else {
        FiveYear = F
        ThreeYear = F
        OneYear = F
      }
      entYear <- data.frame(Entity.ID = e, Year = entityYearsVector[i], OneYearRetention = OneYear,
                            ThreeYearRetention = ThreeYear, FiveYearRetention = FiveYear)
      fulldata <- bind_rows(fulldata, entYear)
      r = r + 1
      if(r%%10000 == 0) {
        print(r)
      }
    }
  }
  fulldata
}

byYear2 <- RetainedByYear()
head(byYear)
b <- Sys.time()
b - a
```

