---
title: "DonorRetentionWorkingCode"
author: "Owen Salciccioli, Kristin Prunty, Rachel Holman"
date: "10/5/2022"
output: html_document
---

### Load in Libraries
```{r}
library(tidyverse)
library(ggplot2)
library(dplyr)
library(readxl)
library(lubridate)
library(ggthemes)
library(devtools)
```

### Read in Data
```{r}
Rel_Type <- read.csv("1_4_Relationship_Type.csv")
Part_Hist <- read.csv("1_5a_Participation_History.csv")
DH1 <- read.csv("DonorHistoryFirstThree")
DH2 <- read.csv("DonorHistorySecondThree")
DH3 <- read.csv("DonorHistoryThirdThree")
DH4 <- read.csv("DonorHistoryFourthThree")
DH5 <- read.csv("DonorHistoryFifthThree")
DH6 <- read.csv("DonorHistorySixthThree")
DH7 <- read.csv("DonorHistoryLastTwo")
```

### Fix relationship spreadsheet
```{r}
Rel_Type_Split <- Rel_Type %>%
  mutate(value = 1) %>%
  pivot_wider(names_from = Relationship.Type, values_from = value)

Rel_Type_Split[is.na(Rel_Type_Split)] <- 0 
## https://stackoverflow.com/questions/8161836/how-do-i-replace-na-values-with-zeros-in-an-r-dataframe%5C
```

## Fix participationship spreadsheet
```{r}
Part_Hist_Split <- Part_Hist %>%
  select(!c(4:7)) %>%
  mutate(Participation.Category = case_when(Participation.Category == "" ~ "Uncategorized",
                                            TRUE ~ Participation.Category)) %>%
  pivot_wider(names_from = Participation.Category, values_from = Activity.Name, values_fn = list)
```

### Clean and add data to Donor History
```{r}
DonorHistory <- cbind(DH1, DH2, DH3, DH4, DH5, DH6, DH7)

remove("DH1", "DH2", "DH3", "DH4", "DH5", "DH6", "DH7")

DonorHistory_Clean <- DonorHistory %>%
  select(!3) %>%
  left_join(Rel_Type_Split) %>%
  left_join(Part_Hist_Split)
```


# create retention variables for 1, 3, and 5 years
```{r}

```


# eda on destination school and designation purpose
# eda on scholarship data (psch in purpose)
# maybe over time
```{r}
 # library
library(ggplot2)
 
# Stacked bar graph- credit amount by year grouped by designation purpose
# Focus on Yellow because it relates to scholarships
ggplot(DonorHistory_Clean, aes(fill=Designation.Purpose, y=Credit.Amount, x=Fiscal.Year)) + 
  geom_bar(position="stack", stat="identity") +
  scale_fill_brewer(palette="Set1") +
  scale_y_continuous(labels=scales::dollar_format())

# Stacked bar graph- credit amount by designation purpose colored by year
# More red = more recent donations
ggplot(DonorHistory_Clean, aes(fill=Fiscal.Year, y=Credit.Amount, x=Designation.Purpose)) + 
  geom_bar(position="stack", stat="identity") +
  scale_fill_gradient(low = "lightyellow", high="red") +
  scale_y_continuous(labels=scales::dollar_format())
```


```{r}
# new dataset grpuped by f.year and designation to fix order of color

# Stacked bar graph- credit amount by designation school colored by year
# More red = more recent donations
ggplot(DonorHistory_Clean, aes(fill=Fiscal.Year, y=Credit.Amount, x=Designation.School.Unit)) + 
  geom_bar(position="stack", stat="identity") +
  scale_fill_gradientn(colours = heat.colors(5), trans = "reverse") +
  scale_y_continuous(labels=scales::dollar_format())
```


```{r}
# Stacked bar graph- credit amount by transaction type stacked by designation purpose
# Focus on Yellow because it relates to scholarships
ggplot(DonorHistory_Clean, aes(fill=Designation.Purpose, y=Credit.Amount, x=Transaction.Type.Code)) + 
  geom_bar(position="stack", stat="identity") +
  scale_fill_brewer(palette="Set1") +
  scale_y_continuous(labels=scales::dollar_format())
```



```{r, fig.height=5, fig.width=10, fig.align='center', warning=FALSE, message=FALSE}
temp <- DonorHistory_Clean %>%
  mutate(Processing.Date1  = mdy(Processing.Date))

ggplot(aes(x=Processing.Date1, y=Credit.Amount, group=1),size=1, data= temp) +
  geom_line(color="blue") +
  scale_y_continuous(name="Case Count", labels=scales::comma)+
  scale_x_date(breaks=waiver(), name="Date")+
  ggtitle("Credit Amount Over Time",
          subtitle = "subtitle")+
  theme_stata(scheme = "s1mono") +
  scale_colour_stata("mono")+
  theme(plot.title = element_text(hjust=0.5),
        plot.subtitle = element_text(hjust=0.5)) +
  theme(axis.text.x = element_text(face="bold", color="slateblue", size=10, angle=45),
        axis.text.y = element_text(face="bold", color="slateblue", size=10, angle=45)) +
  theme(panel.background = element_rect(fill="snow"))

# add limit to y axis - cap at $10,000,000 - to see trends better
ggplot(aes(x=Processing.Date1, y=Credit.Amount, group=1),size=1, data= temp) +
  geom_line(color="blue") +
  scale_y_continuous(name="Case Count", labels=scales::comma, limits = c(0,10000000))+
  scale_x_date(breaks=waiver(), name="Date")+
  ggtitle("Credit Amount Over Time",
          subtitle = "subtitle")+
  theme_stata(scheme = "s1mono") +
  scale_colour_stata("mono")+
  theme(plot.title = element_text(hjust=0.5),
        plot.subtitle = element_text(hjust=0.5)) +
  theme(axis.text.x = element_text(face="bold", color="slateblue", size=10, angle=45),
        axis.text.y = element_text(face="bold", color="slateblue", size=10, angle=45)) +
  theme(panel.background = element_rect(fill="snow"))

# for better idea of time of year most popular for donations, look at one year at a time

```


```{r, warning=FALSE}
# average credit amount by month and year 
temp2 <- DonorHistory_Clean %>%
  mutate(Processing_Date  = mdy(Processing.Date),
         Year = year(mdy(Processing.Date)),
         Month = month(mdy(Processing.Date))) %>%
  group_by(Year, Month) %>%
  mutate(meanCreditAmount=mean(Credit.Amount))

ggplot(aes(x=Processing_Date, y=meanCreditAmount),size=1, data=temp2) +  
  geom_line(color="blue") +
  labs(x="Year", y="Credit Amount")+
  scale_y_continuous(labels=scales::comma)+
  ggtitle("Average Monthly Credit Amount ", 
          subtitle ="subtitle")+
  theme_stata()+
  theme(plot.title = element_text(hjust=0.5),
        plot.subtitle = element_text(hjust=0.5)) +
  theme(axis.text.x = element_text(face="bold", color="slateblue", size=10, angle=45),
        axis.text.y = element_text(face="bold", color="slateblue", size=10, angle=45))


#average credit amount by month overall
temp3 <- DonorHistory_Clean %>%
  mutate(Processing_Date  = mdy(Processing.Date),
         Month = month(mdy(Processing.Date), label=TRUE, abbr=TRUE)) %>%
  group_by(Month) %>%
  mutate(meanCreditAmount=mean(Credit.Amount))

ggplot(aes(x=Month, y=meanCreditAmount, group=1),size=1, data=temp3) +  
  geom_point(size=2) +
  geom_line(color="blue") +
  labs(x="Month", y="Credit Amount")+
  scale_y_continuous(labels=scales::comma)+
  ggtitle("Average Monthly Credit Amount ", 
          subtitle ="subtitle")+
  theme_stata()+
  theme(plot.title = element_text(hjust=0.5),
        plot.subtitle = element_text(hjust=0.5)) +
  theme(axis.text.x = element_text(face="bold", color="slateblue", size=10, angle=45),
        axis.text.y = element_text(face="bold", color="slateblue", size=10, angle=45))

```



```{r}
## New reponse variables being produced for analysis:
# 1 year max retention count (most consecutive years retained)
# 3 year max retention count (most consecutive sets of 3 years retained)
# 5 year max retention count (most consecutive sets of 5 years retained)

#zip codes and majors info coming soon - predictors

#
```



 

# random forest
```{r random forest, eval=FALSE}
# Installing package
#install.packages("caTools")       # For sampling the dataset
#install.packages("randomForest")  # For implementing random forest algorithm
  
# Loading package
library(caTools)
library(randomForest)

# Splitting data in train and test data
split <- sample.split(DonorHistory_Clean, SplitRatio = 0.7)
split
  
train <- subset(DonorHistory_Clean, split == "TRUE")
test <- subset(DonorHistory_Clean, split == "FALSE")
  
# Fitting Random Forest to the train dataset
set.seed(120)  # Setting seed
classifier_RF = randomForest(x = train[-5],
                             y = train$yvar, #add the yvar of Retention when created
                             ntree = 500)
  
classifier_RF
  
# Predicting the Test set results
y_pred = predict(classifier_RF, newdata = test[-5])
  
# Confusion Matrix
confusion_mtx = table(test[, 5], y_pred)
confusion_mtx
  
# Plotting model
plot(classifier_RF)
  
# Importance plot
importance(classifier_RF)
  
# Variable importance plot
varImpPlot(classifier_RF)

```
 




