---
title: "DonorRetentionWorkingCode"
author: "Owen Salciccioli, Kristin Prunty, Rachel Holman"
date: "10/5/2022"
output: html_document
---

### Load in Libraries
```{r}
library(tidyverse)
library(caret)
library(randomForest)
library(lubridate)
library(ggthemes)
```

### Read in Data
```{r}
Rel_Type <- read.csv("1_4_Relationship_Type.csv")
Part_Hist <- read.csv("1_5a_Participation_History.csv")
Addresses <- read.csv("1_2a_Addresses.csv")
Majors <- read.csv("1_3_Degrees.csv")
DH1 <- read.csv("DonorHistoryFirstThree")
DH2 <- read.csv("DonorHistorySecondThree")
DH3 <- read.csv("DonorHistoryThirdThree")
DH4 <- read.csv("DonorHistoryFourthThree")
DH5 <- read.csv("DonorHistoryFifthThree")
DH6 <- read.csv("DonorHistorySixthThree")
DH7 <- read.csv("DonorHistoryLastTwo")
RetentionIndicators <- read.csv("retentionIndicators.csv")
```

### Clean retention data
```{r}
Retention <- RetentionIndicators %>%
  mutate(OneYear = as.numeric(OneYearRetention),
         ThreeYear = as.numeric(ThreeYearRetention),
         FiveYear = as.numeric(FiveYearRetention),
         FiscalYear = year(ymd(Year, truncated = 2))) %>%
  select(!c(OneYearRetention, ThreeYearRetention, FiveYearRetention, Year))

RetentionLong <- Retention %>%
  pivot_longer(cols = c(OneYear, ThreeYear, FiveYear), names_to = "RetainedType", values_to = "RetainedCount")
```

### Fix relationship spreadsheet
```{r}
Rel_Type_Split <- Rel_Type %>%
  mutate(value = 1) %>%
  pivot_wider(names_from = Relationship.Type, values_from = value)

Rel_Type_Split[is.na(Rel_Type_Split)] <- 0 
## https://stackoverflow.com/questions/8161836/how-do-i-replace-na-values-with-zeros-in-an-r-dataframe%5C
```

## Fix participation spreadsheet
```{r}
Part_Hist_Split <- Part_Hist %>%
  select(!c(4:7)) %>%
  mutate(Participation.Category = case_when(Participation.Category == "" ~ "Uncategorized",
                                            TRUE ~ Participation.Category)) %>%
  pivot_wider(names_from = Participation.Category, values_from = Activity.Name, values_fn = list)
```

### Fix addresses spreadsheet
```{r}
#select relevant variables
Addresses <- Addresses %>%
  mutate(newZip = str_extract(Zip, "\\d+?(?=-)")) %>%
  select(Entity.ID, newZip, Country) %>%
  rename(Zip = newZip)

#find duplicate Entities
b <- rle(sort(Addresses$Entity.ID))
adCounts <- data.frame(ID=b$values, count=b$lengths)
dupEID <- adCounts %>%
  filter(count > 1) 

#subset only duplicates
DupAd <- Addresses %>%
  filter(Entity.ID %in% dupEID$ID)

#remove duplicates from full data
Addresses <- Addresses %>%
  filter(!(Entity.ID %in% dupEID$ID))

#loop through duplicates and combine matches
i = 1
while (i < (nrow(DupAd))) {
  if(DupAd$Entity.ID[i] == DupAd$Entity.ID[i+1]) {
    if(is.na(DupAd$Zip[i]) || is.na(DupAd$Zip[i+1])) {
      if (DupAd$Country[i] == DupAd$Country[i+1]) {
        DupAd <- DupAd[-c(i),]
      }
    } else if(DupAd$Zip[i] == DupAd$Zip[i+1]) {
      DupAd <- DupAd[-c(i),]
    }
  }
  i = i + 1
}

#find remaining duplicates(couldn't be combined)
c <- rle(sort(DupAd$Entity.ID))
adCounts2 <- data.frame(ID=c$values, count=c$lengths)
dupEID2 <- adCounts2 %>%
  filter(count > 1) 

#new subset of non-match duplicates
DupAd2 <- DupAd %>%
  filter(Entity.ID %in% dupEID2$ID)

#combined duplicates
DupAd <- DupAd %>%
  filter(!(Entity.ID %in% dupEID2$ID))

#add now combined duplicates to original data
Addresses <- rbind(Addresses, DupAd)

```

###Fix majors spreadsheet
```{r}
Majors_new <- Majors %>%
  select(!c(4)) %>%
  mutate(School.of.Graduation = case_when(School.of.Graduation == "" ~ "No College",
                                            TRUE ~ School.of.Graduation)) %>%
  pivot_wider(id_cols= Entity.ID, names_from = School.of.Graduation, values_from = Major, values_fn = list, unused_fn = max)

```

### Clean and add data to Donor History
```{r}
DonorHistory <- cbind(DH1, DH2, DH3, DH4, DH5, DH6, DH7)

remove("DH1", "DH2", "DH3", "DH4", "DH5", "DH6", "DH7")

DonorHistory_Clean <- DonorHistory %>%
  select(!3) %>%
  left_join(Rel_Type_Split) %>%
  left_join(Part_Hist_Split) %>%
  left_join(Addresses) %>%
  left_join(Majors_new, by=c('Entity.ID')) %>%
  filter(!is.na(Entity.ID))
```

### Create active donor and retention variables
```{r}
a <- rle(sort(DonorHistory_Clean$Entity.ID))
counts <- data.frame(ID=a$values, count=a$lengths)

retainedAtAll <- counts %>%
  mutate(retainedAtAll = ifelse(count > 1, 1, 0)) %>%
  select(!count)

## https://stackoverflow.com/questions/1923273/counting-the-number-of-elements-with-the-values-of-x-in-a-vector

DonorHistoryRetention <- DonorHistory_Clean %>%
  mutate(Active = ifelse(Fiscal.Year %in% c(2022, 2023), 1, 0)) %>%
  left_join(retainedAtAll, by = c("Entity.ID" = "ID"))
```

## Code to create retention variables - DO NOT RUN, just pull dataset from GIT
```{r}
# a <- Sys.time()
# findYears <- function(e) {
#   entityYears <- DonorHistory_Clean %>%
#     filter(Entity.ID == e) %>%
#     select(Fiscal.Year) %>%
#     arrange(Fiscal.Year)
#   entityYearsVector = as.vector(entityYears[,1])
#   entityYearsVector
# }
# 
# 
# RetainedByYear <- function() {
#   uniqueEntity <- unique(DonorHistory_Clean$Entity.ID)
#   fulldata <- data.frame('Entity.ID'=character(), 'Year'= integer(), 
#                          'OneYearRetention'= logical(), 'ThreeYearRetention'= logical(), 'FiveYearRetention'= logical())
#   r = 1
#   for (e in uniqueEntity) {
#     entityYearsVector <- unique(findYears(e))
#     for (i in 1:length(entityYearsVector)) {
#       if (i == 1) {
#         OneYear = F
#         ThreeYear = F
#         FiveYear = F
#       }
#       else if(entityYearsVector[i] - entityYearsVector[i-1] == 1) {
#         OneYear = T
#         ThreeYear = T
#         FiveYear = T
#       }
#       else if (entityYearsVector[i] - entityYearsVector[i-1] <= 3) {
#         ThreeYear = T
#         FiveYear = T
#         OneYear = F
#       }
#       else if (entityYearsVector[i] - entityYearsVector[i-1] <= 5) {
#         FiveYear = T
#         ThreeYear = F
#         OneYear = F
#       }
#       else {
#         FiveYear = F
#         ThreeYear = F
#         OneYear = F
#       }
#       entYear <- data.frame(Entity.ID = e, Year = entityYearsVector[i], OneYearRetention = OneYear, 
#                             ThreeYearRetention = ThreeYear, FiveYearRetention = FiveYear)
#       fulldata <- bind_rows(fulldata, entYear)
#       r = r + 1
#       if(r%%10000 == 0) {
#         print(r)
#       }
#     }
#   }
#   fulldata
# }
# 
# byYear <- RetainedByYear()
# head(byYear)
# b <- Sys.time()
# b - a
```

```{r}
TotalsRetained <- RetentionLong %>%
  group_by(FiscalYear, RetainedType) %>%
  summarize(donors = length(Entity.ID), retained = sum(RetainedCount))
  
shift <- function(x,n) {
  c(x[-(seq(n))], rep(NA, n))
}

TotalsRetained$retained <- shift(TotalsRetained$retained, 3)

TotalsRetained$FiscalYear <- shift(TotalsRetained$FiscalYear, 3)

PercentRetained <- TotalsRetained %>%
  filter(FiscalYear != 2023) %>%
  mutate(PercentRetained = retained/donors)
```

### Retention Graphs
```{r}
ggplot(data = filter(Retention, FiscalYear > 2009 & FiscalYear < 2023)) +
  geom_col(aes(x = FiscalYear, y = OneYear))

ggplot(data = filter(PercentRetained, RetainedType == "OneYear")) +
  theme_wsj() +
  geom_col(aes(x = FiscalYear, y = PercentRetained)) +
  geom_text(aes(x = FiscalYear, y = PercentRetained + .02, 
                label = round(100 * PercentRetained, 1)),
            color = "red", size = 3)  +
  scale_y_continuous(breaks = c(0, .2, .4, .6, .8, 1), labels = c(0, 20, 40, 60, 80, 100)) +
  ylab("Percent Retained") +
  xlab("Fiscal Year") +
  coord_cartesian(ylim = c(0,.80)) +
  labs(title = "1 Year Donor Retention Over the Years") +
  theme(title = element_text(size = 14))
```

