---
title: "Graphs"
author: "Owen Salciccioli, Kristin Prunty, Rachel Holman"
date: "10/5/2022"
output: html_document
---

### Load in Libraries
```{r}
library(tidyverse)
library(ggplot2)
library(dplyr)
library(readxl)
library(lubridate)
library(ggthemes)
library(devtools)
library(RColorBrewer)
```

### Read in Data 
```{r}
source('DataCleaning.R')
head(DonorHistoryRetention)
head(RetDataPercLong) 
head(RetDataScholPercLong)
```


## Filter the data into Annual Fund Donations (those less than $10,000)
```{r}
# make donor hist with only credit amount < 10,000
DonorHistory_AF <- DonorHistoryRetention[which(DonorHistoryRetention$Credit.Amount < 10000),]
```



# EDA

## Stacked Bar Graphs
```{r}
 
# Stacked bar graph- credit amount by year grouped by designation purpose
# Focus on Yellow because it relates to scholarships
ggplot(DonorHistoryRetention, aes(fill=Designation.Purpose, y=Credit.Amount, x=Fiscal.Year)) + 
  geom_bar(position="stack", stat="identity") +
  ggtitle("Donation Amount over Time by Purpose", subtitle = "All Donations")+
  labs(x="Fiscal Year", y="Credit Amount", fill="Designation Purpose")+
  scale_fill_brewer(palette="Set1") +
  scale_y_continuous(labels=scales::dollar_format()) +
  theme(plot.title = element_text(hjust=0.5),
        plot.subtitle = element_text(hjust=0.5)) 

# Same as stacked bar graph above, but for only annual fund donations
ggplot(DonorHistory_AF, aes(fill=Designation.Purpose, y=Credit.Amount, x=Fiscal.Year)) + 
  geom_bar(position="stack", stat="identity") +
  ggtitle("Donation Amount over Time by Purpose", subtitle = "Donations < $10,000")+
  labs(x="Fiscal Year", y="Credit Amount", fill="Designation Purpose")+
  scale_fill_brewer(palette="Set1") +
  scale_y_continuous(labels=scales::dollar_format())+
  theme(plot.title = element_text(hjust=0.5),
        plot.subtitle = element_text(hjust=0.5)) 

```

```{r}
# making color palette larger
nb.cols <- 22
mycolors <- colorRampPalette(brewer.pal(8, "Spectral"))(nb.cols)

# Stacked bar graph- credit amount by designation purpose colored by year
# More red = more recent donations
ggplot(DonorHistoryRetention, aes(fill=factor(Fiscal.Year), y=Credit.Amount, x=Designation.Purpose)) + 
  geom_bar(position="stack", stat="identity") +
  ggtitle("Total Donation Amount by Purpose", subtitle = "All Donations")+
  labs(x="Designation Purpose", y="Credit Amount", fill="Fiscal Year")+
  scale_fill_manual(values= rev(mycolors)) +
  scale_y_continuous(labels=scales::dollar_format())+
  theme(plot.title = element_text(hjust=0.5),
        plot.subtitle = element_text(hjust=0.5))

# Same as stacked bar graph above, but for only annual fund donations
ggplot(DonorHistory_AF, aes(fill=factor(Fiscal.Year), y=Credit.Amount, x=Designation.Purpose)) + 
  geom_bar(position="stack", stat="identity") +
  ggtitle("Total Donation Amount by Purpose", subtitle = "Donations < $10,000")+
  labs(x="Designation Purpose", y="Credit Amount", fill="Fiscal Year")+
  scale_fill_manual(values= rev(mycolors)) +
  scale_y_continuous(labels=scales::dollar_format())+
  theme(plot.title = element_text(hjust=0.5),
        plot.subtitle = element_text(hjust=0.5))
```



```{r, fig.width=10}
# Stacked bar graph- credit amount by designation school colored by year
# More red = more recent donations
ggplot(DonorHistoryRetention, aes(fill=factor(Fiscal.Year), y=Credit.Amount, x=Designation.School.Unit)) + 
  geom_bar(position="stack", stat="identity") +
  ggtitle("Total Donation Amount by School", subtitle = "All Donations")+
  labs(x="Designation School", y="Credit Amount", fill="Fiscal Year")+
  scale_fill_manual(values = rev(mycolors)) +
  scale_y_continuous(labels=scales::dollar_format())+
  theme(plot.title = element_text(hjust=0.5),
        plot.subtitle = element_text(hjust=0.5))

# Same as stacked bar graph above, but for only annual fund donations
ggplot(DonorHistory_AF, aes(fill=factor(Fiscal.Year), y=Credit.Amount, x=Designation.School.Unit)) + 
  geom_bar(position="stack", stat="identity") +
  ggtitle("Total Donation Amount by School", subtitle = "Donations < $10,000")+
  labs(x="Designation School", y="Credit Amount", fill="Fiscal Year")+
  scale_fill_manual(values = rev(mycolors)) +
  scale_y_continuous(labels=scales::dollar_format())+
  theme(plot.title = element_text(hjust=0.5),
        plot.subtitle = element_text(hjust=0.5))
```


```{r, fig.width=8}
# Stacked bar graph- credit amount by transaction type stacked by designation purpose
# Focus on Yellow because it relates to scholarships
ggplot(DonorHistoryRetention, aes(fill=Designation.Purpose, y=Credit.Amount, x=Transaction.Type.Code)) + 
  geom_bar(position="stack", stat="identity") +
  ggtitle("Donation Amount per Transaction Type by Purpose", subtitle = "All Donations")+
  labs(x="Transaction Type", y="Credit Amount", fill="Designation Purpose")+
  scale_fill_brewer(palette="Set1") +
  scale_y_continuous(labels=scales::dollar_format())+
  theme(plot.title = element_text(hjust=0.5),
        plot.subtitle = element_text(hjust=0.5))

# Same as stacked bar graph above, but for only annual fund donations
ggplot(DonorHistory_AF, aes(fill=Designation.Purpose, y=Credit.Amount, x=Transaction.Type.Code)) + 
  geom_bar(position="stack", stat="identity") +
  ggtitle("Donation Amount per Transaction Type by Purpose", subtitle = "Donations < $10,000")+
  labs(x="Transaction Type", y="Credit Amount", fill="Designation Purpose")+
  scale_fill_brewer(palette="Set1") +
  scale_y_continuous(labels=scales::dollar_format())+
  theme(plot.title = element_text(hjust=0.5),
        plot.subtitle = element_text(hjust=0.5))
```


## Line Graphs over Time

```{r, warning=FALSE}
# create temp dataframe with average credit amount and average donation count by month and year
temp2 <- DonorHistory_AF %>%
  mutate(Transaction_Date  = mdy(Transaction.Date),
         Year = year(mdy(Transaction.Date)),
         Month = month(mdy(Transaction.Date))) %>%
  group_by(Year, Month) %>%
  mutate(meanCreditAmount=mean(Credit.Amount),
         donationCount = n()/2)

# line graph with average monthly credit amount over time
ggplot(aes(x=Transaction_Date, y=meanCreditAmount),size=1, data=temp2) +  
  geom_line(color="blue") +
  labs(x="Year", y="Credit Amount")+
  scale_y_continuous(labels=scales::comma)+
  ggtitle("Average Monthly Credit Amount ", 
          subtitle ="Based on Transaction Date")+
  theme_stata()+
  theme(plot.title = element_text(hjust=0.5),
        plot.subtitle = element_text(hjust=0.5)) +
  theme(axis.text.x = element_text(face="bold", color="slateblue", size=10, angle=45),
        axis.text.y = element_text(face="bold", color="slateblue", size=10, angle=45))

# line graph with average monthly donation count over time
ggplot(aes(x=Transaction_Date, y=donationCount),size=1, data=temp2) +  
  geom_line(color="blue") +
  labs(x="Year", y="Number of Donations")+
  scale_y_continuous(labels=scales::comma)+
  ggtitle("Average Monthly Donation Count", 
          subtitle ="Based on Transaction Date")+
  theme_stata()+
  theme(plot.title = element_text(hjust=0.5),
        plot.subtitle = element_text(hjust=0.5)) +
  theme(axis.text.x = element_text(face="bold", color="slateblue", size=10, angle=45),
        axis.text.y = element_text(face="bold", color="slateblue", size=10, angle=45))


# 2017-2023 to see covid impact
# line graph with average monthly credit amount over 2017-2023
ggplot(aes(x=Transaction_Date, y=meanCreditAmount),size=1, data=temp2) +  
  geom_line(color="blue") +
  labs(x="Year", y="Credit Amount")+
  scale_y_continuous(labels=scales::comma)+
  scale_x_date(limits = as.Date(c("2017-01-01","2023-04-30")))+
  ggtitle("Average Monthly Credit Amount ", 
          subtitle ="Based on Transaction Date")+
  theme_stata()+
  theme(plot.title = element_text(hjust=0.5),
        plot.subtitle = element_text(hjust=0.5)) +
  theme(axis.text.x = element_text(face="bold", color="slateblue", size=10, angle=45),
        axis.text.y = element_text(face="bold", color="slateblue", size=10, angle=45))

# line graph with average monthly donation count over 2017-2023
ggplot(aes(x=Transaction_Date, y=donationCount),size=1, data=temp2) +  
  geom_line(color="blue") +
  labs(x="Year", y="Number of Donations")+
  scale_y_continuous(labels=scales::comma)+
  scale_x_date(limits = as.Date(c("2017-01-01","2023-04-30")))+
  ggtitle("Average Monthly Donation Count ", 
          subtitle ="Based on Transaction Date")+
  theme_stata()+
  theme(plot.title = element_text(hjust=0.5),
        plot.subtitle = element_text(hjust=0.5)) +
  theme(axis.text.x = element_text(face="bold", color="slateblue", size=10, angle=45),
        axis.text.y = element_text(face="bold", color="slateblue", size=10, angle=45))

```


```{r, warning=FALSE}
# create temp dataframe with average credit amount and average donation count by fiscal year
temp3 <- DonorHistory_AF %>%
  mutate(Transaction_Date  = mdy(Transaction.Date),
         Year = year(mdy(Transaction.Date)),
         Month = month(mdy(Transaction.Date))) %>%
  group_by(Fiscal.Year) %>%
  mutate(meanCreditAmount=mean(Credit.Amount),
         totalCreditAmount=sum(Credit.Amount),
         donationCount = n()/21)

# line graph with average yearly credit amount over time
ggplot(aes(x=Fiscal.Year, y=meanCreditAmount),size=1, data=temp3) + 
  geom_point(size=1) +
  geom_line(color="blue") +
  labs(x="Year", y="Donation Amount")+
  scale_y_continuous(labels=scales::comma)+
  scale_x_continuous(limits = (c(2002,2022)), n.breaks = 11)+
  ggtitle("Average Yearly Donation Amount ", 
          subtitle ="Based on Fiscal Year")+
  geom_segment(aes(x=2008, xend=2008, y=0, yend=250), linetype=2) +
  annotate(geom = "text", x = 2008, y = 260, label = "Market Crash", hjust = "right")+
  geom_segment(aes(x=2020, xend=2020, y=0, yend=250), linetype=2) +
  annotate(geom = "text", x = 2020, y = 260, label = "Covid Outbreak", hjust = "right")+
  theme_stata()+
  theme(plot.title = element_text(hjust=0.5),
        plot.subtitle = element_text(hjust=0.5)) +
  theme(axis.text.x = element_text(face="bold", color="slateblue", size=10, angle=45),
        axis.text.y = element_text(face="bold", color="slateblue", size=10, angle=45))

# line graph with average yearly donation count over time
ggplot(aes(x=Fiscal.Year, y=donationCount),size=1, data=temp3) +  
  geom_point(size=1) +
  geom_line(color="blue") +
  labs(x="Year", y="Number of Donations")+
  scale_y_continuous(labels=scales::comma)+
  scale_x_continuous(limits = (c(2002,2022)), n.breaks = 11)+
  ggtitle("Yearly Donation Count", 
          subtitle ="Based on Fiscal Year")+
  geom_segment(aes(x=2008, xend=2008, y=0, yend=56000), linetype=2) +
  annotate(geom = "text", x = 2008, y = 58000, label = "Market Crash", hjust = "right")+
  geom_segment(aes(x=2020, xend=2020, y=0, yend=56000), linetype=2) +
  annotate(geom = "text", x = 2020, y = 58000, label = "Covid Outbreak", hjust = "right")+
  theme_stata()+
  theme(plot.title = element_text(hjust=0.5),
        plot.subtitle = element_text(hjust=0.5)) +
  theme(axis.text.x = element_text(face="bold", color="slateblue", size=10, angle=45),
        axis.text.y = element_text(face="bold", color="slateblue", size=10, angle=45))


# 2017-2022 to see covid impact
# line graph with average yearly credit amount over 2017-2022
ggplot(aes(x=Fiscal.Year, y=meanCreditAmount),size=1, data=temp3) + 
  geom_point(size=1) +
  geom_line(color="blue") +
  labs(x="Year", y="Donation Amount")+
  scale_y_continuous(labels=scales::comma)+
  scale_x_continuous(limits = (c(2017,2022)), n.breaks = 7)+
  ggtitle("Average Yearly Donation Amount ", 
          subtitle ="Based on Fiscal Year")+
  theme_stata()+
  theme(plot.title = element_text(hjust=0.5),
        plot.subtitle = element_text(hjust=0.5)) +
  theme(axis.text.x = element_text(face="bold", color="slateblue", size=10, angle=45),
        axis.text.y = element_text(face="bold", color="slateblue", size=10, angle=45))

# line graph with average yearly donation count over 2017-2022
ggplot(aes(x=Fiscal.Year, y=donationCount),size=1, data=temp3) +  
  geom_point(size=1) +
  geom_line(color="blue") +
  labs(x="Year", y="Number of Donations")+
  scale_y_continuous(labels=scales::comma)+
  scale_x_continuous(limits = (c(2017,2022)), n.breaks = 7)+
  ggtitle("Yearly Donation Count ", 
          subtitle ="Based on Fiscal Year")+
  theme_stata()+
  theme(plot.title = element_text(hjust=0.5),
        plot.subtitle = element_text(hjust=0.5)) +
  theme(axis.text.x = element_text(face="bold", color="slateblue", size=10, angle=45),
        axis.text.y = element_text(face="bold", color="slateblue", size=10, angle=45))

# line graph with total yearly credit amount over 2017-2022
ggplot(aes(x=Fiscal.Year, y=totalCreditAmount),size=1, data=temp3) + 
  geom_point(size=1) +
  geom_line(color="blue") +
  labs(x="Year", y="Donation Amount")+
  scale_y_continuous(labels=scales::comma)+
  scale_x_continuous(limits = (c(2002,2022)), n.breaks = 11)+
  ggtitle("Total Yearly Donation Amount ", 
          subtitle ="Based on Fiscal Year")+
  theme_stata()+
  theme(plot.title = element_text(hjust=0.5),
        plot.subtitle = element_text(hjust=0.5)) +
  theme(axis.text.x = element_text(face="bold", color="slateblue", size=10, angle=45),
        axis.text.y = element_text(face="bold", color="slateblue", size=10, angle=45))
```


```{r, warning=FALSE}
# create temp dataframe with average credit amount by month based on processing date
temp4 <- DonorHistory_AF %>%
  mutate(Processing_Date  = mdy(Processing.Date),
         Month = month(mdy(Processing.Date), label=TRUE, abbr=TRUE)) %>%
  group_by(Month) %>%
  mutate(meanCreditAmount=mean(Credit.Amount))

# line graph with average monthly credit amount based on processing date
ggplot(aes(x=Month, y=meanCreditAmount, group=1),size=1, data=temp4) +  
  geom_point(size=2) +
  geom_line(color="blue") +
  labs(x="Month", y="Donation Amount")+
  scale_y_continuous(labels=scales::comma)+
  ggtitle("Average Monthly Donation Amount ", 
          subtitle ="Based on Processing Date")+
  theme_stata()+
  theme(plot.title = element_text(hjust=0.5),
        plot.subtitle = element_text(hjust=0.5)) +
  theme(axis.text.x = element_text(face="bold", color="slateblue", size=10, angle=45),
        axis.text.y = element_text(face="bold", color="slateblue", size=10, angle=45))


# create temp dataframe with average credit amount by month based on transaction date
temp5 <- DonorHistory_AF %>%
  mutate(Transaction_Date  = mdy(Transaction.Date),
         Month = month(mdy(Transaction.Date), label=TRUE, abbr=TRUE)) %>%
  group_by(Month) %>%
  mutate(meanCreditAmount=mean(Credit.Amount))

# line graph with average monthly credit amount based on transaction date
ggplot(aes(x=Month, y=meanCreditAmount, group=1),size=1, data=temp5) +  
  geom_point(size=2) +
  geom_line(color="blue") +
  labs(x="Month", y="Donation Amount")+
  scale_y_continuous(labels=scales::comma)+
  ggtitle("Average Monthly Donation Amount ", 
          subtitle ="Based on Transaction Date for Donations < $10,000")+
  theme_stata()+
  theme(plot.title = element_text(hjust=0.5),
        plot.subtitle = element_text(hjust=0.5)) +
  theme(axis.text.x = element_text(face="bold", color="slateblue", size=10, angle=45),
        axis.text.y = element_text(face="bold", color="slateblue", size=10, angle=45))

# create temp dataframe with donation count by month based on transaction date
temp6 <- DonorHistory_AF %>%
  mutate(Transaction_Date  = mdy(Transaction.Date),
         Month = month(mdy(Transaction.Date), label=TRUE, abbr=TRUE)) %>%
  group_by(Month) %>%
  summarise(donationCount = n())

# convert donation count into an average- dividing by different number of years besed on fiscal year distribution
temp6_2 <- temp6 %>%
  mutate(donationCount = case_when(Month %in% c("Oct", "Nov", "Dec") ~ donationCount/20, TRUE ~ donationCount/21 ))

# line graph with average monthly donation count based on transaction date
ggplot(aes(x=Month, y=donationCount, group=1),size=1, data=temp6_2) +  
  geom_point(size=2) +
  geom_line(color="blue") +
  labs(x="Month", y="Number of Donations")+
  scale_y_continuous(labels=scales::comma)+
  ggtitle("Average Monthly Donation Count ", 
          subtitle ="Based on Transaction Date for Donations < $10,000")+
  theme_stata()+
  theme(plot.title = element_text(hjust=0.5),
        plot.subtitle = element_text(hjust=0.5)) +
  theme(axis.text.x = element_text(face="bold", color="slateblue", size=10, angle=45),
        axis.text.y = element_text(face="bold", color="slateblue", size=10, angle=45))
```


```{r, warning=FALSE}
#same as plots avobe but for all donations (useful for comparison)
temp5.1 <- DonorHistoryRetention %>%
  mutate(Transaction_Date  = mdy(Transaction.Date),
         Month = month(mdy(Transaction.Date), label=TRUE, abbr=TRUE)) %>%
  group_by(Month) %>%
  mutate(meanCreditAmount=mean(Credit.Amount))

ggplot(aes(x=Month, y=meanCreditAmount, group=1),size=1, data=temp5.1) +  
  geom_point(size=2) +
  geom_line(color="blue") +
  labs(x="Month", y="Donation Amount")+
  scale_y_continuous(labels=scales::comma)+
  ggtitle("Average Monthly Donation Amount ", 
          subtitle ="Based on Transaction Date for all Donations")+
  theme_stata()+
  theme(plot.title = element_text(hjust=0.5),
        plot.subtitle = element_text(hjust=0.5)) +
  theme(axis.text.x = element_text(face="bold", color="slateblue", size=10, angle=45),
        axis.text.y = element_text(face="bold", color="slateblue", size=10, angle=45))


temp6.1 <- DonorHistoryRetention %>%
  mutate(Transaction_Date  = mdy(Transaction.Date),
         Month = month(mdy(Transaction.Date), label=TRUE, abbr=TRUE)) %>%
  group_by(Month) %>%
  mutate(donationCount=n())

ggplot(aes(x=Month, y=donationCount, group=1),size=1, data=temp6.1) +  
  geom_point(size=2) +
  geom_line(color="blue") +
  labs(x="Month", y="Number of Donations")+
  scale_y_continuous(labels=scales::comma)+
  ggtitle("Average Monthly Donation Count ", 
          subtitle ="Based on Transaction Date for all Donations")+
  theme_stata()+
  theme(plot.title = element_text(hjust=0.5),
        plot.subtitle = element_text(hjust=0.5)) +
  theme(axis.text.x = element_text(face="bold", color="slateblue", size=10, angle=45),
        axis.text.y = element_text(face="bold", color="slateblue", size=10, angle=45))
```



## Owen's graphs:

```{r}
temp6OwenAllYears <- DonorHistory_AF %>%
  mutate(Transaction_Date  = mdy(Transaction.Date),
         Month = month(mdy(Transaction.Date), label=TRUE, abbr=TRUE),
         Year = year(mdy(Transaction.Date))) %>%
  group_by(Month, Year) %>%
  summarize(donationCount= n()) %>%
  filter(!(Month == "Oct" & Year == 2022))

temp6OwenAverageMonth <- DonorHistory_AF %>%
  mutate(Transaction_Date  = mdy(Transaction.Date),
         Month = month(mdy(Transaction.Date), label=TRUE, abbr=TRUE),
         Year = year(mdy(Transaction.Date))) %>%
  group_by(Month) %>%
  summarize(donationCount= n()) %>%
  mutate(donationCount = case_when(Month %in% c("Oct", "Nov", "Dec") ~ donationCount/20, TRUE ~ donationCount/21))


ggplot(aes(x=Month, y=donationCount, group= Year), data=temp6OwenAllYears) + 
  theme_bw() +
  geom_line(data = filter(temp6OwenAllYears, Year < 2019), color="grey80") +
  geom_line(data = filter(temp6OwenAllYears, Year == 2019), color="blue") +
  geom_line(data = filter(temp6OwenAllYears, Year > 2019), color="red") +
  geom_line(data = temp6OwenAverageMonth, aes(y = donationCount, x = Month, group = 1), inherit = FALSE) +
  # annotate("rect", xmin = "Jun", xmax = "Sep", ymin = 6000, ymax = 8100, fill = "white", hjust = 1) +
  annotate("text", x = "Jun", y = 8000, label = "Pre COVID (Before 2019)", color = "grey50", hjust = 0, vjust = 1) +
  annotate("text", x = "Jun", y = 7600, label = "2019", color = "blue", hjust = 0, vjust = 1) +
  annotate("text", x = "Jun", y = 7200, label = "COVID (After 2019)", color = "red", hjust = 0, vjust = 1) +
  annotate("text", x = "Jun", y = 6800, label = "Average", color = "black", hjust = 0, vjust = 1) +
  labs(x = "Month", y = "Number of Donations") +
  ggtitle("Average Monthly Annual Fund Donation Count ", 
          subtitle ="Based on Transaction Date for Donations < $10,000") +
  coord_cartesian(expand = FALSE, ylim = (c(0,8200)))
```

### Monthly annual fund donors
```{r}
temp6_1OwenAllYears <- DonorHistory_AF %>%
  mutate(Transaction_Date  = mdy(Transaction.Date),
         Month = month(mdy(Transaction.Date), label=TRUE, abbr=TRUE),
         Year = year(mdy(Transaction.Date))) %>%
  group_by(Month, Year) %>%
  summarize(meanCreditAmount = mean(Credit.Amount)) %>%
  filter(!(Month == "Oct" & Year == 2022))

temp6_1OwenAverageMonth <- DonorHistory_AF %>%
  mutate(Transaction_Date  = mdy(Transaction.Date),
         Month = month(mdy(Transaction.Date), label=TRUE, abbr=TRUE),
         Year = year(mdy(Transaction.Date))) %>%
  group_by(Month) %>%
  summarize(meanCreditAmount = mean(Credit.Amount))


ggplot(aes(x=Month, y=meanCreditAmount, group= Year), data=temp6_1OwenAllYears) + 
  theme_bw() +
  geom_line(data = filter(temp6_1OwenAllYears, Year < 2019), color="grey80") +
  geom_line(data = filter(temp6_1OwenAllYears, Year == 2019), color="blue") +
  geom_line(data = filter(temp6_1OwenAllYears, Year > 2019), color="red") +
  geom_line(data = temp6_1OwenAverageMonth, aes(y = meanCreditAmount, x = Month, group = 1), inherit = FALSE) +
  # annotate("rect", xmin = "Jun", xmax = "Sep", ymin = 6000, ymax = 8100, fill = "white", hjust = 1) +
  annotate("text", x = "Jun", y = 450, label = "Pre COVID (Before 2019)", color = "grey50", hjust = 0, vjust = 1) +
  annotate("text", x = "Jun", y = 430, label = "2019", color = "blue", hjust = 0, vjust = 1) +
  annotate("text", x = "Jun", y = 410, label = "COVID (After 2019)", color = "red", hjust = 0, vjust = 1) +
  annotate("text", x = "Jun", y = 390, label = "Average", color = "black", hjust = 0, vjust = 1) +
  labs(x = "Month", y = "Amount of Donation ($)") +
  ggtitle("Average Monthly Donation Amount ", 
          subtitle ="Based on Transaction Date for Donations < $10,000") +
  coord_cartesian(expand = FALSE)
```

### Retention Graphs
```{r}
## Plotting annual fund retention
ggplot(RetDataPercLong) +
  theme_stata() +
  geom_line(aes(x = year, y = percent, color = RetentionType), size = 1.5) +
  geom_point(aes(x = year, y = percent, color = RetentionType), size = 1.5) +
  #geom_text(aes(x = year, y = percent + .02, 
  #             label = round(100 * PercentRetained, 1)),
  #         color = "red", size = 3)  +
  scale_y_continuous(breaks = c(0, .2, .4, .6, .8, 1), labels = c(0, 20, 40, 60, 80, 100), minor_breaks = c(.1, .3, .5, .7, .9)) +
  scale_x_continuous(n.breaks = 11) +
  scale_color_discrete(labels = c("One Year", "Three Year", "Five Year")) +
  ylab("Percent Retained") +
  xlab("Fiscal Year") +
  coord_cartesian(ylim = c(0,1), xlim = c(2001.75, 2022), expand = FALSE) +
  labs(title = "Donor Retention", subtitle = "Percentage of Annual Fund donors in a given year who returned in following years") +
  theme(plot.title = element_text(size = 18), plot.subtitle = element_text(size = 12), legend.position = "right", legend.title = element_blank(), text = element_text(hjust = .5))

## Plotting scholarship retention
ggplot(data = RetDataScholPercLong) +
  theme_stata() +
  geom_line(aes(x = year, y = percent, color = RetentionType), size = 1.5) +
  geom_point(aes(x = year, y = percent, color = RetentionType), size = 1.5) +
  #geom_text(aes(x = year, y = percent + .02, 
   #             label = round(100 * PercentRetained, 1)),
   #         color = "red", size = 3)  +
  scale_y_continuous(breaks = c(0, .2, .4, .6, .8, 1), labels = c(0, 20, 40, 60, 80, 100), minor_breaks = c(.1, .3, .5, .7, .9)) +
  scale_x_continuous(n.breaks = 11) +
  scale_color_discrete(labels = c("One Year", "Three Year", "Five Year")) +
  ylab("Percent Retained") +
  xlab("Fiscal Year") +
  coord_cartesian(ylim = c(0,1), xlim = c(2001.75, 2022), expand = FALSE) +
  labs(title = "Scholarship Donor Retention", subtitle = "Percentage of Annual Fund donors in a given year who returned in following years") +
  theme(plot.title = element_text(size = 18), plot.subtitle = element_text(size = 12), legend.position = "right", legend.title = element_blank(), text = element_text(hjust = .5))
```


```{r}
# space for any next plot/graph
# likely for when we do EDA for address and major data
```
 

